
title: "Blog — Studio di Ingegneria dell'Informazione Pasquale Cavallo"
description: "Note su progettazione, cloud, IoT, DevOps, KPI e ROI."
theme: jekyll-theme-slate
# URL will be set automatically by GitHub Pages; set baseurl only if you publish under a project site
# url: "https://blog.pasqualecavallo.it"
# baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Minima options
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/
    - platform: linkedin
      user_url: https://www.linkedin.com/

# Markdown & code highlighting
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Navigation (optional)
# header_pages:
#   - about.md
